name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: my-step
        run: echo "Hello robo!"
        
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.14.0-alpha.0"

      # Install dependencies (Robot Framework and Selenium Library)
      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium

  
      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget curl
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo dpkg -i google-chrome.deb
          sudo apt --fix-broken install -y

      # Install ChromeDriver (matching Chrome version)
      - name: Install ChromeDriver
        run: |
          # Get the major version of Chrome (e.g., 131)
          CHROME_MAJOR_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Chrome major version: $CHROME_MAJOR_VERSION"
          
          # Get the corresponding ChromeDriver version using the LATEST_RELEASE endpoint
          CHROMEDRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION)
          
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Error: Unable to find matching ChromeDriver version."
            exit 1
          fi
          
          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install the corresponding ChromeDriver version
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/  # Make chromedriver available in PATH


      # Run Robot Framework tests
      - name: Run Robot Framework tests
        run: |
          robot test.robot
