name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: my-step
        run: echo "Hello robo!"
        
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.14.0-alpha.0"

      # Install dependencies (Robot Framework and Selenium Library)
      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium

  
    # Install Microsoft Edge
      - name: Install Microsoft Edge
        run: |
          sudo apt update
          sudo apt install -y wget curl
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt update
          sudo apt install -y microsoft-edge-stable

      # Install Edge WebDriver (matching Edge version)
      - name: Install Edge WebDriver
        run: |
          # Get the major version of Edge (e.g., 131)
          EDGE_MAJOR_VERSION=$(microsoft-edge --version | awk '{print $3}' | cut -d'.' -f1)
          echo "Detected Edge major version: $EDGE_MAJOR_VERSION"
          
          # Get the corresponding Edge WebDriver version using the LATEST_RELEASE endpoint
          EDGE_DRIVER_VERSION=$(curl -sSL https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_MAJOR_VERSION)
          
          if [ -z "$EDGE_DRIVER_VERSION" ]; then
            echo "Error: Unable to find matching Edge WebDriver version."
            exit 1
          fi
          
          echo "Using Edge WebDriver version: $EDGE_DRIVER_VERSION"
          
          # Download and install the corresponding Edge WebDriver version
          wget https://msedgedriver.azureedge.net/$EDGE_DRIVER_VERSION/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/  # Make msedgedriver available in PATH

      # Run Robot Framework tests
      - name: Run Robot Framework tests
        run: |
          robot test.robot
